/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as NewsRouteImport } from './routes/news'
import { Route as WpCheckRouteImport } from './routes/wp-check'
import { Route as WpCheckResultRouteImport } from './routes/wp-check-result'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as TopicsIndexRouteImport } from './routes/topics.index'
import { Route as TopicsTopicRouteImport } from './routes/topics.$topic'
import { Route as AuthenticatedDocumentsIdRouteImport } from './routes/_authenticated/documents.$id'
import { Route as ApiPublicNewsRouteImport } from './routes/api/public/news'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const WpCheckRoute = WpCheckRouteImport.update({
  id: '/wp-check',
  path: '/wp-check',
  getParentRoute: () => rootRouteImport,
} as any)
const WpCheckResultRoute = WpCheckResultRouteImport.update({
  id: '/wp-check-result',
  path: '/wp-check-result',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const TopicsIndexRoute = TopicsIndexRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsTopicRoute = TopicsTopicRouteImport.update({
  id: '/topics/$topic',
  path: '/topics/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDocumentsIdRoute =
  AuthenticatedDocumentsIdRouteImport.update({
    id: '/documents/$id',
    path: '/documents/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicNewsRoute = ApiPublicNewsRouteImport.update({
  id: '/api/public/news',
  path: '/api/public/news',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/news': typeof NewsRoute
  '/wp-check': typeof WpCheckRoute
  '/wp-check-result': typeof WpCheckResultRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/topics/$topic': typeof TopicsTopicRoute
  '/topics/': typeof TopicsIndexRoute
  '/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/api/public/news': typeof ApiPublicNewsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/news': typeof NewsRoute
  '/wp-check': typeof WpCheckRoute
  '/wp-check-result': typeof WpCheckResultRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/topics/$topic': typeof TopicsTopicRoute
  '/topics': typeof TopicsIndexRoute
  '/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/api/public/news': typeof ApiPublicNewsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/news': typeof NewsRoute
  '/wp-check': typeof WpCheckRoute
  '/wp-check-result': typeof WpCheckResultRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/topics/$topic': typeof TopicsTopicRoute
  '/topics/': typeof TopicsIndexRoute
  '/_authenticated/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/api/public/news': typeof ApiPublicNewsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/news'
    | '/wp-check'
    | '/wp-check-result'
    | '/admin'
    | '/topics/$topic'
    | '/topics/'
    | '/documents/$id'
    | '/api/public/news'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/news'
    | '/wp-check'
    | '/wp-check-result'
    | '/admin'
    | '/topics/$topic'
    | '/topics'
    | '/documents/$id'
    | '/api/public/news'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/news'
    | '/wp-check'
    | '/wp-check-result'
    | '/_authenticated/admin'
    | '/topics/$topic'
    | '/topics/'
    | '/_authenticated/documents/$id'
    | '/api/public/news'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  NewsRoute: typeof NewsRoute
  WpCheckRoute: typeof WpCheckRoute
  WpCheckResultRoute: typeof WpCheckResultRoute
  TopicsTopicRoute: typeof TopicsTopicRoute
  TopicsIndexRoute: typeof TopicsIndexRoute
  ApiPublicNewsRoute: typeof ApiPublicNewsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wp-check': {
      id: '/wp-check'
      path: '/wp-check'
      fullPath: '/wp-check'
      preLoaderRoute: typeof WpCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wp-check-result': {
      id: '/wp-check-result'
      path: '/wp-check-result'
      fullPath: '/wp-check-result'
      preLoaderRoute: typeof WpCheckResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/topics/': {
      id: '/topics/'
      path: '/topics'
      fullPath: '/topics/'
      preLoaderRoute: typeof TopicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$topic': {
      id: '/topics/$topic'
      path: '/topics/$topic'
      fullPath: '/topics/$topic'
      preLoaderRoute: typeof TopicsTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/documents/$id': {
      id: '/_authenticated/documents/$id'
      path: '/documents/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof AuthenticatedDocumentsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/news': {
      id: '/api/public/news'
      path: '/api/public/news'
      fullPath: '/api/public/news'
      preLoaderRoute: typeof ApiPublicNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDocumentsIdRoute: typeof AuthenticatedDocumentsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDocumentsIdRoute: AuthenticatedDocumentsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  NewsRoute: NewsRoute,
  WpCheckRoute: WpCheckRoute,
  WpCheckResultRoute: WpCheckResultRoute,
  TopicsTopicRoute: TopicsTopicRoute,
  TopicsIndexRoute: TopicsIndexRoute,
  ApiPublicNewsRoute: ApiPublicNewsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
